import Head from "next/head";
import Image from "next/image";
import {
  Edit3,
  Heart,
  Package,
  Briefcase,
  MessageCircle,
  Mail,
  Linkedin,
  GitHub,
  Twitter,
} from "react-feather";
import { DevDotToArticle } from "@/types/devDotTo";
import Tippy from "@tippyjs/react";

export const getStaticProps = async () => {
  const res = await fetch("https://dev.to/api/articles?username=ajones_codes");
  const articles = (await res.json()) as DevDotToArticle[];
  // sort the articles by top public reactions and get the first 5
  const trimmedArticles = articles
    .filter((article) => !article.title.includes("Reddit"))
    // .sort((a, b) => {
    //   return b.public_reactions_count - a.public_reactions_count;
    // })
    .slice(0, 7);

  const articleReactionCounts: Record<string, number> = {};

  const reactionFetchPromises: Promise<any>[] = [];

  trimmedArticles.forEach((article) => {
    reactionFetchPromises.push(
      fetch("https://dev.to/reactions?article_id=" + article.id)
        .then((res) => res.json())
        .then((articleReactionsJson) => {
          articleReactionCounts[article.id] = (
            articleReactionsJson.article_reaction_counts as Array<{
              count: number;
            }>
          ).reduce<number>((sum, reactionType) => {
            console.log(sum, reactionType);
            return sum + reactionType.count;
          }, 0);
        })
    );
  });
  await Promise.all(reactionFetchPromises);

  const trimmedSortedArticles = trimmedArticles.sort((a, b) => {
    return articleReactionCounts[b.id] - articleReactionCounts[a.id];
  });

  return {
    props: {
      articles: trimmedSortedArticles,
      articleReactionCounts,
    },
  };
};

export default function Home({
  articles,
  articleReactionCounts,
}: {
  articles: DevDotToArticle[];
  articleReactionCounts: Record<string, number>;
}) {
  return (
    <>
      <Head>
        <title>Andrew Jones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-left px-4 md:px-24 lg:px-36">
        <div className="container pt-24 border-b-2">
          <h1 className="text-6xl font-bold">Andrew Jones</h1>
          <h2 className="text-2xl mt-4 mb-2">
            Software Engineer | Problem Solver | Teacher | Speaker
          </h2>
        </div>
        <div className="pt-12" id="content-grid">
          <Edit3 size={48} className={"inline-block mr-8 lg:mr-24"} />
          <div>
            <h2 className="text-4xl mb-2">Writing</h2>
            <ul>
              {articles.map((article) => {
                return (
                  <Tippy
                    key={article.id}
                    content={
                      <div className="bg-black w-[300px] rounded-md">
                        {article.cover_image ? (
                          <Image
                            src={article.cover_image}
                            alt={"article image"}
                            width={300}
                            height={200}
                            className="rounded-t-md"
                          ></Image>
                        ) : null}
                        <div className="p-2">
                          <p>{article.title}</p>
                          <p className="text-gray-400">
                            {article.reading_time_minutes} minute read
                          </p>
                        </div>
                      </div>
                    }
                  >
                    <li id={`article-${article.id}`}>
                      <a
                        href={article.canonical_url}
                        target="_blank"
                        rel="noreferrer"
                        className="text-lg no-underline hover:underline"
                      >
                        {article.title}
                      </a>
                      <div className="flex mb-6">
                        <span style={{ color: "#aaa" }} className="mr-2">
                          {articleReactionCounts[article.id]} reactions
                          {/* {article.public_reactions_count} |{" "}
                        {new Date(article.readable_publish_date)
                          .toISOString()
                          .substring(0, 10)} */}
                        </span>
                      </div>
                    </li>
                  </Tippy>
                );
              })}
            </ul>
          </div>
          <Package size={48} className={"inline-block mr-8 lg:mr-24"} />
          <div>
            <h2 className="text-4xl mb-2">Projects</h2>
            <ul>
              <Tippy
                content={
                  <div className="bg-black w-[300px] rounded-md">
                    <Image
                      src={"/covid_dashboard.png"}
                      alt={
                        "COVID Dashboard screenshot showing graphs of COVID-19 data"
                      }
                      width={300}
                      height={200}
                      className="rounded-t-md"
                    ></Image>
                    <div className="p-2">
                      <p>COVID-19 Research Dashboard</p>
                      <p className="text-gray-400">built with React</p>
                    </div>
                  </div>
                }
              >
                <li className="mt-3 mb-5">
                  <h2 className="text-xl">Open-Source Full-Stack AI Chat</h2>
                  <p>
                    I developed a full-stack AI chat application similar to
                    ChatGPT but with extra UI features like split-screen,
                    searching messages, and message suggestions. This is a
                    full-stack project built with Next.js, PlanetScaleDB, Clerk
                    auth, and TailwindCSS. Since launching it, I have taken
                    open-source contributions from other developers.
                  </p>
                </li>
              </Tippy>
              <Tippy
                content={
                  <div className="bg-black w-[300px] rounded-md">
                    <Image
                      src={"/covid_dashboard.png"}
                      alt={
                        "COVID Dashboard screenshot showing graphs of COVID-19 data"
                      }
                      width={300}
                      height={200}
                      className="rounded-t-md"
                    ></Image>
                    <div className="p-2">
                      <p>COVID-19 Research Dashboard</p>
                      <p className="text-gray-400">built with React</p>
                    </div>
                  </div>
                }
              >
                <li className="mt-3 mb-5">
                  <h2 className="text-xl">COVID-19 Research</h2>
                  <p>
                    I led a research project on the system dynamics of the
                    global spread of COVID-19, which culminated in{" "}
                    <a
                      href="https://doi.org/10.1016/j.chaos.2020.110376"
                      target="_blank"
                      rel="noreferrer"
                    >
                      a paper published
                    </a>{" "}
                    in an Elsevier journal. I developed{" "}
                    <a
                      href="https://chaotic-covid19.vercel.app/"
                      target="_blank"
                      rel="noreferrer"
                      id="covid-dashboard"
                    >
                      a data analysis dashboard
                    </a>{" "}
                    in JavaScript which the project centered around.
                  </p>
                </li>
              </Tippy>
              <Tippy
                content={
                  <div className="bg-black w-[300px] rounded-md">
                    <Image
                      src={"/sharesheets.png"}
                      alt={
                        "Screenshots showing a contact sharing app with a QR scanner and fields for different social media accounts"
                      }
                      width={300}
                      height={200}
                      className="rounded-t-md"
                    ></Image>
                    <div className="p-2">
                      <p>Screenshots of the app</p>
                      <p className="text-gray-400">built with React Native</p>
                    </div>
                  </div>
                }
              >
                <li id="sharesheets-item" className="mb-5">
                  <h2 className="text-xl">ShareSheets</h2>
                  <p>
                    ShareSheets allows users to share their contact information
                    and social media accounts by creating and scanning QR codes.
                    It is cross-platform (iPhone, iPad, and Android), and
                    completely written in React Native using an Expo-managed
                    workflow. Check it out on the{" "}
                    <a href="https://apps.apple.com/tt/app/sharesheets/id1493143639">
                      iOS App Store
                    </a>{" "}
                    or{" "}
                    <a href="https://play.google.com/store/apps/details?id=com.aej11.sharesheets&hl=en_US&gl=US">
                      Google Play Store.
                    </a>
                  </p>
                </li>
              </Tippy>
            </ul>
          </div>
          <Briefcase size={48} className={"inline-block mr-8 lg:mr-24"} />
          <div>
            <h2 className="text-4xl mb-2">Professional Experience</h2>
            <ul>
              <li className="mt-3 mb-5">
                <h2 className="text-xl">Engineering Manager @ Corra</h2>
                <p>
                  On the forefront of an exciting paradigm shift in the
                  e-commerce industry, I lead the development of{" "}
                  <a href="https://corra.com/lp/pylot/">Pylot</a>, a reference
                  storefront for headless, composable commerce implementations.
                  I&apos;ve had the pleasure of managing and mentoring a team of
                  React and Node.js devs working on enterprise-level e-commerce
                  implementations for clients. I also work with Corra&apos;s
                  marketing, sales, and leadership teams to strategically grow
                  our headless commerce portfolio. Please reach out to me,{" "}
                  <a href="mailto:ajones@corra.com">ajones@corra.com</a>, or{" "}
                  <a href="https://corra.com/contact/">via our website</a>, if
                  you&apos;re looking for an SI to work with!
                </p>
              </li>
            </ul>
          </div>
          <MessageCircle size={48} className={"inline-block mr-8 lg:mr-24"} />
          <div>
            <h2 className="text-4xl mb-2">Connect with Me</h2>
            <ul className="flex flex-wrap">
              <li className="mt-3 mb-5 mr-4">
                <h2 className="text-xl">Email</h2>
                <p>
                  <a href="mailto:aej11@outlook.com">aej11@outlook.com</a>
                </p>
              </li>
              <li className="mt-3 mb-5 mr-4">
                <a
                  href="https://www.linkedin.com/in/ajones55"
                  className="no-underline"
                >
                  <h2 className="text-xl">LinkedIn</h2>
                  <p>
                    <Linkedin />
                  </p>
                </a>
              </li>
              <li className="mt-3 mb-5 mr-4">
                <a href="https://github.com/aej11a" className="no-underline">
                  <h2 className="text-xl">GitHub</h2>
                  <p>
                    <GitHub />
                  </p>
                </a>
              </li>
              <li className="mt-3 mb-5 mr-4">
                <a
                  href="https://twitter.com/ajones55555"
                  className="no-underline"
                >
                  <h2 className="text-xl">Twitter</h2>
                  <p>
                    <Twitter />
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div style={{ color: "#555" }} className="mt-8 mb-4">
          &copy; Andrew Jones. Built with Next.js and Tailwind CSS.
        </div>
      </main>
    </>
  );
}
